In [5]:
#!pip install kapre


  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for kapre: filename=kapre-0.3.7-py3-none-any.whl size=29602 sha256=aa736d8961e8cdd3ea324bb8b0094994c936c0045413fbb723932542d58702c8
  Stored in directory: /home/dirceusilva/.cache/pip/wheels/b3/04/6b/a7c14b363e7942dad0706127cbf5b5817e51010175fda9026a
Successfully built kapre

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip


In [1]:
import os
import sys
import pathlib
import click
import yaml
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1'


In [2]:
""" trainer.py """
import tensorflow as tf
from tensorflow.keras.utils import Progbar
from model.dataset import Dataset
from model.fp.melspec.melspectrogram import get_melspec_layer
from model.fp.specaug_chain.specaug_chain import get_specaug_chain_layer
from model.fp.nnfp import get_fingerprinter
from model.fp.NTxent_loss_single_gpu import NTxentLoss
from model.fp.online_triplet_loss import OnlineTripletLoss
from model.fp.lamb_optimizer import LAMB
from model.utils.experiment_helper import ExperimentHelper
from model.utils.mini_search_subroutines import mini_search_eval

In [7]:
import pdb

In [3]:
def build_fp(cfg):
    """ Build fingerprinter """
    # m_pre: log-power-Mel-spectrogram layer, S.
    m_pre = get_melspec_layer(cfg, trainable=False)

    # m_specaug: spec-augmentation layer.
    m_specaug = get_specaug_chain_layer(cfg, trainable=False)
    #assert(m_specaug.bypass==False) # Detachable by setting m_specaug.bypass.

    # m_fp: fingerprinter g(f(.)).
    m_fp = get_fingerprinter(cfg, trainable=False)
    return m_pre, m_specaug, m_fp


@tf.function
def train_step(X, m_pre, m_specaug, m_fp, loss_obj, helper):
    """ Train step """
    # X: (Xa, Xp)
    # Xa: anchors or originals, s.t. [xa_0, xa_1,...]
    # Xp: augmented replicas, s.t. [xp_0, xp_1] with xp_n = rand_aug(xa_n).
    n_anchors = len(X[0])
    X = tf.concat(X, axis=0)
    feat = m_specaug(m_pre(X))  # (nA+nP, F, T, 1)
    m_fp.trainable = True
    pdb.set_trace()
    with tf.GradientTape() as t:
        emb = m_fp(feat)  # (BSZ, Dim)
        loss, sim_mtx, _ = loss_obj.compute_loss(
            emb[:n_anchors, :], emb[n_anchors:, :]) # {emb_org, emb_rep}
    g = t.gradient(loss, m_fp.trainable_variables)
    helper.optimizer.apply_gradients(zip(g, m_fp.trainable_variables))
    avg_loss = helper.update_tr_loss(loss) # To tensorboard.
    return avg_loss, sim_mtx # avg_loss: average within the current epoch


@tf.function
def val_step(X, m_pre, m_fp, loss_obj, helper):
    """ Validation step """
    n_anchors = len(X[0])
    X = tf.concat(X, axis=0)
    feat = m_pre(X)  # (nA+nP, F, T, 1)
    m_fp.trainable = False
    emb = m_fp(feat)  # (BSZ, Dim)
    loss, sim_mtx, _ = loss_obj.compute_loss(
        emb[:n_anchors, :], emb[n_anchors:, :]) # {emb_org, emb_rep}
    avg_loss = helper.update_val_loss(loss) # To tensorboard.
    return avg_loss, sim_mtx


@tf.function
def test_step(X, m_pre, m_fp):
    """ Test step used for mini-search-validation """
    X = tf.concat(X, axis=0)
    feat = m_pre(X)  # (nA+nP, F, T, 1)
    m_fp.trainable = False
    emb_f = m_fp.front_conv(feat)  # (BSZ, Dim)
    emb_f_postL2 = tf.math.l2_normalize(emb_f, axis=1)
    emb_gf = m_fp.div_enc(emb_f)
    emb_gf = tf.math.l2_normalize(emb_gf, axis=1)
    return emb_f, emb_f_postL2, emb_gf # f(.), L2(f(.)), L2(g(f(.))


def mini_search_validation(ds, m_pre, m_fp, mode='argmin',
                           scopes=[1, 3, 5, 9, 11, 19], max_n_samples=3000):
    """ Mini-search-validation """
    # Construct mini-DB
    key_strs = ['f', 'L2(f)', 'g(f)']
    m_fp.trainable = False
    (db, query, emb, dim) = (dict(), dict(), dict(), dict())
    dim['f'] = dim['L2(f)'] = m_fp.front_hidden_ch[-1]
    dim['g(f)'] = m_fp.emb_sz
    bsz = ds.bsz
    n_anchor = bsz // 2
    n_iter = min(len(ds), max_n_samples // bsz)
    for k in key_strs:
        (db[k], query[k]) = (tf.zeros((0, dim[k])), tf.zeros((0, dim[k])))
    for i in range(n_iter):
        X = ds.__getitem__(i)
        emb['f'], emb['L2(f)'], emb['g(f)'] = test_step(X, m_pre, m_fp)
        for k in key_strs:
            db[k] = tf.concat((db[k], emb[k][:n_anchor, :]), axis=0)
            query[k] = tf.concat((query[k], emb[k][n_anchor:, :]), axis=0)

    # Search test
    accs_by_scope = dict()
    for k in key_strs:
        tf.print(f'======= mini-search-validation: \033[31m{mode} \033[33m{k} \033[0m=======' + '\033[0m')
        query[k] = tf.expand_dims(query[k], axis=1) # (nQ, d) --> (nQ, 1, d)
        accs_by_scope[k], _ = mini_search_eval(
            query[k], db[k], scopes, mode, display=True)
    return accs_by_scope, scopes, key_strs


def trainer(cfg, checkpoint_name):
    # Dataloader
    dataset = Dataset(cfg)

    # Build models.
    m_pre, m_specaug, m_fp = build_fp(cfg)

    # Learning schedule
    total_nsteps = cfg['TRAIN']['MAX_EPOCH'] * len(dataset.get_train_ds())
    if cfg['TRAIN']['LR_SCHEDULE'].upper() == 'COS':
        lr_schedule = tf.keras.experimental.CosineDecay(
            initial_learning_rate=float(cfg['TRAIN']['LR']),
            decay_steps=total_nsteps,
            alpha=1e-06)
    elif cfg['TRAIN']['LR_SCHEDULE'].upper() == 'COS-RESTART':
        lr_schedule = tf.keras.experimental.CosineDecayRestarts(
            initial_learning_rate=float(cfg['TRAIN']['LR']),
            first_decay_steps=int(total_nsteps * 0.1),
            num_periods=0.5,
            alpha=2e-06)
    else:
        lr_schedule = float(cfg['TRAIN']['LR'])

    # Optimizer
    if cfg['TRAIN']['OPTIMIZER'].upper() == 'LAMB':
        opt = LAMB(learning_rate=lr_schedule)
    elif cfg['TRAIN']['OPTIMIZER'].upper() == 'ADAM':
        opt = tf.keras.optimizers.Adam(learning_rate=lr_schedule)
    else:
        raise NotImplementedError(cfg['TRAIN']['OPTIMIZER'])

    # Experiment helper: see utils.experiment_helper.py for details.
    helper = ExperimentHelper(
        checkpoint_name=checkpoint_name,
        optimizer=opt,
        model_to_checkpoint=m_fp,
        cfg=cfg)

    # Loss objects
    if cfg['LOSS']['LOSS_MODE'].upper() == 'NTXENT': # Default
        loss_obj_train = NTxentLoss(
            n_org=cfg['BSZ']['TR_N_ANCHOR'],
            n_rep=cfg['BSZ']['TR_BATCH_SZ'] - cfg['BSZ']['TR_N_ANCHOR'],
            tau=cfg['LOSS']['TAU'])
        loss_obj_val = NTxentLoss(
            n_org=cfg['BSZ']['VAL_N_ANCHOR'],
            n_rep=cfg['BSZ']['VAL_BATCH_SZ'] - cfg['BSZ']['VAL_N_ANCHOR'],
            tau=cfg['LOSS']['TAU'])
    elif cfg['LOSS']['LOSS_MODE'].upper() == 'ONLINE-TRIPLET': # Now-playing
        loss_obj_train = OnlineTripletLoss(
            bsz=cfg['BSZ']['TR_BATCH_SZ'],
            n_anchor=cfg['BSZ']['TR_N_ANCHOR'],
            mode = 'semi-hard',
            margin=cfg['LOSS']['MARGIN'])
        loss_obj_val = OnlineTripletLoss(
            bsz=cfg['BSZ']['VAL_BATCH_SZ'],
            n_anchor=cfg['BSZ']['VAL_N_ANCHOR'],
            mode = 'all', # use 'all' mode for validation
            margin=0.)
    else:
        raise NotImplementedError(cfg['LOSS']['LOSS_MODE'])

    # Training loop
    ep_start = helper.epoch
    ep_max = cfg['TRAIN']['MAX_EPOCH']
    for ep in range(ep_start, ep_max + 1):
        tf.print(f'EPOCH: {ep}/{ep_max}')

        # Train
        """ Parallelism to speed up preprocessing.............. """
        train_ds = dataset.get_train_ds(cfg['DATA_SEL']['REDUCE_ITEMS_P'])
        progbar = Progbar(len(train_ds))
        enq = tf.keras.utils.OrderedEnqueuer(
            train_ds, use_multiprocessing=True, shuffle=train_ds.shuffle)
        enq.start(workers=cfg['DEVICE']['CPU_N_WORKERS'],
                  max_queue_size=cfg['DEVICE']['CPU_MAX_QUEUE'])
        i = 0
        while i < len(enq.sequence):
            X = next(enq.get()) # X: Tuple(Xa, Xp)
            avg_loss, sim_mtx = train_step(X, m_pre, m_specaug, m_fp,
                                            loss_obj_train, helper)
            progbar.add(1, values=[("tr loss", avg_loss)])
            i += 1
        enq.stop()
        """ End of Parallelism................................. """

        if cfg['TRAIN']['SAVE_IMG'] and (sim_mtx is not None):
            helper.write_image_tensorboard('tr_sim_mtx', sim_mtx.numpy())

        # Validate
        """ Parallelism to speed up preprocessing.............. """
        val_ds = dataset.get_val_ds(max_song=250) # max 500
        enq = tf.keras.utils.OrderedEnqueuer(
            val_ds, use_multiprocessing=True, shuffle=False)
        enq.start(workers=cfg['DEVICE']['CPU_N_WORKERS'],
                  max_queue_size=cfg['DEVICE']['CPU_MAX_QUEUE'])
        i = 0
        while i < len(enq.sequence):
            X = next(enq.get()) # X: Tuple(Xa, Xp)
            _, sim_mtx = val_step(X, m_pre, m_fp, loss_obj_val,
                                  helper)
            i += 1
        enq.stop()
        """ End of Parallelism................................. """

        if cfg['TRAIN']['SAVE_IMG'] and (sim_mtx is not None):
            helper.write_image_tensorboard('val_sim_mtx', sim_mtx.numpy())

        # On epoch end
        tf.print('tr_loss:{:.4f}, val_loss:{:.4f}'.format(
            helper._tr_loss.result(), helper._val_loss.result()))
        helper.update_on_epoch_end(save_checkpoint_now=True)


        # Mini-search-validation (optional)
        if cfg['TRAIN']['MINI_TEST_IN_TRAIN']:
            accs_by_scope, scopes, key_strs = mini_search_validation(
                val_ds, m_pre, m_fp)
            for k in key_strs:
                helper.update_minitest_acc(accs_by_scope[k], scopes, k)

In [4]:
def load_config(config_fname):
    config_filepath = './config/' + config_fname + '.yaml'
    if os.path.exists(config_filepath):
        print(f'cli: Configuration from {config_filepath}')
    else:
        sys.exit(f'cli: ERROR! Configuration file {config_filepath} is missing!!')

    with open(config_filepath, 'r') as f:
        cfg = yaml.safe_load(f)
    return cfg


def update_config(cfg, key1: str, key2: str, val):
    cfg[key1][key2] = val
    return cfg


def print_config(cfg):
    os.system("")
    print('\033[36m' + yaml.dump(cfg, indent=4, width=120, sort_keys=False) +
          '\033[0m')
    return


def train(checkpoint_name, config, max_epoch):
    """ Train a neural audio fingerprinter.

    ex) python run.py train CHECKPOINT_NAME --max_epoch=100

        # with custom config file
        python run.py train CHECKPOINT_NAME --max_epoch=100 -c CONFIG_NAME

    NOTE: If './LOG_ROOT_DIR/checkpoint/CHECKPOINT_NAME already exists, the training will resume from the latest checkpoint in the directory.

    """
    from model.utils.config_gpu_memory_lim import allow_gpu_memory_growth
    from model.trainer import trainer

    cfg = load_config(config)
    if max_epoch: update_config(cfg, 'TRAIN', 'MAX_EPOCH', max_epoch)
    print_config(cfg)
    # allow_gpu_memory_growth()
    trainer(cfg, checkpoint_name)

""" Generate fingerprint (after training) """
def generate(checkpoint_name, checkpoint_index, config, source, output, skip_dummy):
    """ Generate fingerprints from a saved checkpoint.

    ex) python run.py generate CHECKPOINT_NAME

    With custom config: \b\n
        python run.py generate CHECKPOINT_NAME -c CONFIG_NAME

    • If CHECKPOINT_INDEX is not specified, the latest checkpoint in the OUTPUT_ROOT_DIR will be loaded.
    • The default value for the fingerprinting source is [TEST_DUMMY_DB] and [TEST_QUERY_DB] specified in config file.

    """
    from model.utils.config_gpu_memory_lim import allow_gpu_memory_growth
    from model.generate import generate_fingerprint

    cfg = load_config(config)
    allow_gpu_memory_growth()
    generate_fingerprint(cfg, checkpoint_name, checkpoint_index, source, output, skip_dummy)

def evaluate(checkpoint_name, checkpoint_index, config, index_type,
             test_seq_len, test_ids, nogpu):
    """ Search and evalutation.

    ex) python run.py evaluate CHECKPOINT_NAME CHECKPOINT_INDEX

    With options: \b\n

    ex) python run.py evaluate CHECKPOINT_NAME CHEKPOINT_INDEX -i ivfpq -t 3000 --nogpu


    • Currently, the 'evaluate' command does not reference any information other
    than the output log directory from the config file.
    """
    from eval.eval_faiss import eval_faiss

    cfg = load_config(config)
    emb_dir = cfg['DIR']['OUTPUT_ROOT_DIR'] + checkpoint_name + '/' + \
        str(checkpoint_index) + '/'

    if nogpu:
        eval_faiss([emb_dir, "--index_type", index_type, "--test_seq_len",
                    test_seq_len, "--test_ids", test_ids, "--nogpu"])
    else:
        eval_faiss([emb_dir, "--index_type", index_type, "--test_seq_len",
                    test_seq_len, "--test_ids", test_ids])



# **DEBUG**

## **Inicializções**

In [5]:
checkpoint_name:str = "CHECKPOINT"   # string
checkpoint_index:int = None  # int
config:str = "default"       # string 'default'
index_type:str = 'IVFPQ'  # {'L2', 'IVF', 'IVFPQ', " + "'IVFPQ-RR', 'IVFPQ-ONDISK', HNSW'}"
test_seq_len:str =  '11'   # string '1 3 5 9 11 19' segundos 
test_ids:str = "icassp"      # string 'icassp'
nogpu:bool = False         # False or True
max_epoch:int = 5     # int

In [8]:
cfg = load_config(config)
dataset = Dataset(cfg)

cli: Configuration from ./config/default.yaml


**Para perceber os dados no código**

In [7]:
d = dataset.get_train_ds()

In [9]:
len(d)

36365

In [10]:
train_ds = dataset.get_train_ds(cfg['DATA_SEL']['REDUCE_ITEMS_P'])

Criei csv para ver como os dados estão organizados, há músicas com 58 segmentos e outras com 59. Devido à diferença de bytes.

In [145]:
#train_ds.fns_event_seg_list
#dados=train_ds.index_event

#dados=train_ds.fns_bg_seg_list
#dados=train_ds.index_bg

#dados=train_ds.fns_ir_seg_list
#dados=train_ds.index_ir

#train_ds.index_speech #NÃO ESTÁ INCLUIDO NOS RESULTADOS NO ARTIGO

In [11]:
len(dataset.get_train_ds().fns_event_seg_list)

581850

O ```OrderedEnqueuer()``` é usado para processar os dados em batches de forma ordenado. Isto é, processar os dados na mesma ordem que foram fornecidos.
O shuffle serve para baralhar os dados. À POSTERIOR?

In [ ]:
enq = tf.keras.utils.OrderedEnqueuer(train_ds, use_multiprocessing=True, shuffle=train_ds.shuffle)

In [ ]:
enq.start(workers=cfg['DEVICE']['CPU_N_WORKERS'],max_queue_size=cfg['DEVICE']['CPU_MAX_QUEUE'])

In [14]:
print(train_ds.__getitem__(0))

(array([[[ 0.08642578,  0.046875  , -0.26290894, ...,  0.15084839,
          0.1022644 , -0.04901123]],

       [[ 0.0211792 , -0.02392578, -0.03652954, ...,  0.09417725,
          0.10946655,  0.09588623]],

       [[ 0.11630249,  0.20666504,  0.17889404, ...,  0.01394653,
         -0.08651733, -0.00036621]],

       ...,

       [[-0.28250122, -0.27682495, -0.140625  , ..., -0.27990723,
         -0.06842041, -0.12115479]],

       [[-0.08248901, -0.09136963,  0.01858521, ..., -0.01055908,
         -0.00204468, -0.01480103]],

       [[ 0.03213501,  0.03125   ,  0.02627563, ..., -0.09487915,
         -0.11694336, -0.03839111]]], dtype=float32), array([[[-0.05917474,  0.11544432,  0.05569585, ..., -0.03807323,
         -0.04518259,  0.129547  ]],

       [[ 0.3758038 , -0.1149336 , -0.2801483 , ..., -0.22336556,
          0.06892969,  0.50643253]],

       [[-0.2296791 , -0.16798344, -0.11500147, ..., -0.33349124,
         -0.28984046, -0.26033628]],

       ...,

       [[-0.11976889,

In [15]:
train_ds = dataset.get_train_ds(cfg['DATA_SEL']['REDUCE_ITEMS_P'])
progbar = Progbar(len(train_ds))

In [17]:
i = 0

Para chegar ao erro dos ***NaN***:
<br>(Fazer o que ot rainer faz)

In [18]:
m_pre, m_specaug, m_fp = build_fp(cfg)

In [19]:
# Loss objects
if cfg['LOSS']['LOSS_MODE'].upper() == 'NTXENT': # Default
        loss_obj_train = NTxentLoss(
            n_org=cfg['BSZ']['TR_N_ANCHOR'],
            n_rep=cfg['BSZ']['TR_BATCH_SZ'] - cfg['BSZ']['TR_N_ANCHOR'],
            tau=cfg['LOSS']['TAU'])
        loss_obj_val = NTxentLoss(
            n_org=cfg['BSZ']['VAL_N_ANCHOR'],
            n_rep=cfg['BSZ']['VAL_BATCH_SZ'] - cfg['BSZ']['VAL_N_ANCHOR'],
            tau=cfg['LOSS']['TAU'])

In [20]:
total_nsteps = cfg['TRAIN']['MAX_EPOCH'] * len(dataset.get_train_ds())
if cfg['TRAIN']['LR_SCHEDULE'].upper() == 'COS':
        lr_schedule = tf.keras.experimental.CosineDecay(
            initial_learning_rate=float(cfg['TRAIN']['LR']),
            decay_steps=total_nsteps,
            alpha=1e-06)

In [21]:
if cfg['TRAIN']['OPTIMIZER'].upper() == 'ADAM':
        opt = tf.keras.optimizers.Adam(learning_rate=lr_schedule)

In [22]:
helper = ExperimentHelper(
        checkpoint_name=checkpoint_name,
        optimizer=opt,
        model_to_checkpoint=m_fp,
        cfg=cfg)

---Restoring from ./logs/checkpoint/CHECKPOINT/ckpt-100---


In [26]:
X = next(enq.get()) # X: Tuple(Xa, Xp)
avg_loss, sim_mtx = train_step(X, m_pre, m_specaug, m_fp, loss_obj_train, helper)
progbar.add(1, values=[("tr loss", avg_loss)])

Não correr a célula com o while. Não necessário. Depois está dividida em várias células.

In [ ]:
while i < len(enq.sequence):
    X = next(enq.get()) # X: Tuple(Xa, Xp)
    avg_loss, sim_mtx = train_step(X, m_pre, m_specaug, m_fp, loss_obj_train, helper)
    progbar.add(1, values=[("tr loss", avg_loss)])
    i += 1
enq.stop()

In [34]:
train_step(X, m_pre, m_specaug, m_fp, loss_obj_train, helper)

> /tmp/tmpsa5pypkr.py(16)tf__train_step()
     14                 ag__.ld(m_fp).trainable = True
     15                 ag__.ld(pdb).set_trace()
---> 16                 with ag__.ld(tf).GradientTape() as t:
     17                     emb = ag__.converted_call(ag__.ld(m_fp), (ag__.ld(feat),), None, fscope)
     18                     (loss, sim_mtx, _) = ag__.converted_call(ag__.ld(loss_obj).compute_loss, (ag__.ld(emb)[:ag__.ld(n_anchors), :], ag__.ld(emb)[ag__.ld(n_anchors):, :]), None, fscope)

<tf.Tensor 'spec_aug_chainer/PartitionedCall:0' shape=(32, 256, 32, 1) dtype=float32>
--KeyboardInterrupt--

KeyboardInterrupt: Interrupted by user
> /tmp/tmpsa5pypkr.py(16)tf__train_step()
     14                 ag__.ld(m_fp).trainable = True
     15                 ag__.ld(pdb).set_trace()
---> 16                 with ag__.ld(tf).GradientTape() as t:
     17                     emb = ag__.converted_call(ag__.ld(m_fp), (ag__.ld(feat),), None, fscope)
     18                     (loss, sim_m

In [36]:
loss_obj=loss_obj_train

Células essenciais para encontrar o erro:

In [23]:
X = next(enq.get())

In [37]:
""" Train step """
# X: (Xa, Xp)
# Xa: anchors or originals, s.t. [xa_0, xa_1,...]
# Xp: augmented replicas, s.t. [xp_0, xp_1] with xp_n = rand_aug(xa_n).
n_anchors = len(X[0])
X = tf.concat(X, axis=0)
feat = m_specaug(m_pre(X))  # (nA+nP, F, T, 1)
m_fp.trainable = True
with tf.GradientTape() as t:
    emb = m_fp(feat)  # (BSZ, Dim)
    loss, sim_mtx, _ = loss_obj.compute_loss(
        emb[:n_anchors, :], emb[n_anchors:, :]) # {emb_org, emb_rep}
g = t.gradient(loss, m_fp.trainable_variables)
helper.optimizer.apply_gradients(zip(g, m_fp.trainable_variables))
avg_loss = helper.update_tr_loss(loss) # To tensorboard.

In [24]:
n_anchors = len(X[0])

In [25]:
X[1].shape

(16, 1, 8000)

In [26]:
X = tf.concat(X, axis=0)

In [27]:
X.shape

TensorShape([32, 1, 8000])

In [29]:
X

<tf.Tensor: shape=(32, 1, 8000), dtype=float32, numpy=
array([[[-1.4074707e-01, -2.2067261e-01, -2.9251099e-01, ...,
         -5.4437256e-01, -5.9899902e-01, -6.2597656e-01]],

       [[ 1.8615723e-02,  1.6906738e-02, -2.1057129e-03, ...,
         -1.2207031e-04,  1.9836426e-03,  5.6762695e-03]],

       [[ 3.6621094e-04, -3.2873535e-01, -5.8938599e-01, ...,
         -2.9125977e-01, -8.3496094e-01, -3.0117798e-01]],

       ...,

       [[-1.4578062e-01, -1.8511537e-01, -1.9788538e-01, ...,
         -3.0635187e-02, -8.5666180e-02, -8.4085211e-02]],

       [[ 7.5484462e-02,  4.2671114e-03, -3.0220029e-01, ...,
         -4.4676819e-01, -3.6109880e-01, -1.6327396e-01]],

       [[ 7.5484030e-03, -2.8227130e-02, -8.0381058e-02, ...,
          1.1758718e-01,  1.2955016e-01, -2.8872149e-02]]], dtype=float32)>

In [30]:
m_pre(X)

<tf.Tensor: shape=(32, 256, 32, 1), dtype=float32, numpy=
array([[[[-1.769532  ],
         [-1.101128  ],
         [-1.0745572 ],
         ...,
         [-1.4830765 ],
         [-1.5086174 ],
         [-1.3256644 ]],

        [[-1.9381204 ],
         [-1.1754922 ],
         [-1.145031  ],
         ...,
         [-1.7465193 ],
         [-1.6469648 ],
         [-1.4167099 ]],

        [[-1.7804332 ],
         [-1.1693628 ],
         [-1.1604897 ],
         ...,
         [-1.6153746 ],
         [-1.4958944 ],
         [-1.4770952 ]],

        ...,

        [[-2.2276578 ],
         [-2.2438145 ],
         [-2.2582738 ],
         ...,
         [-2.2608    ],
         [-2.175364  ],
         [-2.0337825 ]],

        [[-2.2249455 ],
         [-2.2460814 ],
         [-2.2652597 ],
         ...,
         [-2.2672591 ],
         [-2.1799297 ],
         [-2.038486  ]],

        [[-2.2196138 ],
         [-2.2429776 ],
         [-2.2679245 ],
         ...,
         [-2.2681332 ],
         [-2.18084

In [31]:
m_specaug(m_pre(X))

<tf.Tensor: shape=(32, 256, 32, 1), dtype=float32, numpy=
array([[[[-1.769532  ],
         [-1.101128  ],
         [-1.0745572 ],
         ...,
         [-1.4830765 ],
         [-1.5086174 ],
         [-1.3256644 ]],

        [[-1.9381204 ],
         [-1.1754922 ],
         [-1.145031  ],
         ...,
         [-1.7465193 ],
         [-1.6469648 ],
         [-1.4167099 ]],

        [[-1.7804332 ],
         [-1.1693628 ],
         [-1.1604897 ],
         ...,
         [-1.6153746 ],
         [-1.4958944 ],
         [-1.4770952 ]],

        ...,

        [[-2.2276578 ],
         [-2.2438145 ],
         [-2.2582738 ],
         ...,
         [-2.2608    ],
         [-2.175364  ],
         [-2.0337825 ]],

        [[-2.2249455 ],
         [-2.2460814 ],
         [-2.2652597 ],
         ...,
         [-2.2672591 ],
         [-2.1799297 ],
         [-2.038486  ]],

        [[-2.2196138 ],
         [-2.2429776 ],
         [-2.2679245 ],
         ...,
         [-2.2681332 ],
         [-2.18084

In [32]:
feat = m_specaug(m_pre(X))  # (nA+nP, F, T, 1)

In [33]:
feat

<tf.Tensor: shape=(32, 256, 32, 1), dtype=float32, numpy=
array([[[[-1.769532  ],
         [-1.101128  ],
         [-1.0745572 ],
         ...,
         [-1.4830765 ],
         [-1.5086174 ],
         [-1.3256644 ]],

        [[-1.9381204 ],
         [-1.1754922 ],
         [-1.145031  ],
         ...,
         [-1.7465193 ],
         [-1.6469648 ],
         [-1.4167099 ]],

        [[-1.7804332 ],
         [-1.1693628 ],
         [-1.1604897 ],
         ...,
         [-1.6153746 ],
         [-1.4958944 ],
         [-1.4770952 ]],

        ...,

        [[-2.2276578 ],
         [-2.2438145 ],
         [-2.2582738 ],
         ...,
         [-2.2608    ],
         [-2.175364  ],
         [-2.0337825 ]],

        [[-2.2249455 ],
         [-2.2460814 ],
         [-2.2652597 ],
         ...,
         [-2.2672591 ],
         [-2.1799297 ],
         [-2.038486  ]],

        [[-2.2196138 ],
         [-2.2429776 ],
         [-2.2679245 ],
         ...,
         [-2.2681332 ],
         [-2.18084

In [34]:
m_fp.trainable = True

In [51]:
with tf.GradientTape() as t:
    emb = m_fp(feat)  # (BSZ, Dim)

In [35]:
feat

<tf.Tensor: shape=(32, 256, 32, 1), dtype=float32, numpy=
array([[[[-1.769532  ],
         [-1.101128  ],
         [-1.0745572 ],
         ...,
         [-1.4830765 ],
         [-1.5086174 ],
         [-1.3256644 ]],

        [[-1.9381204 ],
         [-1.1754922 ],
         [-1.145031  ],
         ...,
         [-1.7465193 ],
         [-1.6469648 ],
         [-1.4167099 ]],

        [[-1.7804332 ],
         [-1.1693628 ],
         [-1.1604897 ],
         ...,
         [-1.6153746 ],
         [-1.4958944 ],
         [-1.4770952 ]],

        ...,

        [[-2.2276578 ],
         [-2.2438145 ],
         [-2.2582738 ],
         ...,
         [-2.2608    ],
         [-2.175364  ],
         [-2.0337825 ]],

        [[-2.2249455 ],
         [-2.2460814 ],
         [-2.2652597 ],
         ...,
         [-2.2672591 ],
         [-2.1799297 ],
         [-2.038486  ]],

        [[-2.2196138 ],
         [-2.2429776 ],
         [-2.2679245 ],
         ...,
         [-2.2681332 ],
         [-2.18084

***ERRO:***
<br> (nA+nP, F, T, 1) quando faz a fingerprint/embedding ```m_fp()``` do ```feat``` que é o spec aug.
<br>
<br> m_fp = get_fingerprinter(cfg, trainable=False)

In [36]:
m_fp(feat)

<tf.Tensor: shape=(32, 128), dtype=float32, numpy=
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)>

In [ ]:
with tf.GradientTape() as t:
    emb = m_fp(feat)  # (BSZ, Dim)
    loss, sim_mtx, _ = loss_obj.compute_loss(
        emb[:n_anchors, :], emb[n_anchors:, :]) # {emb_org, emb_rep}

In [ ]:
g = t.gradient(loss, m_fp.trainable_variables)

In [50]:
helper.optimizer.apply_gradients(zip(g, m_fp.trainable_variables))

In [ ]:
avg_loss = helper.update_tr_loss(loss) # To tensorboard.

In [52]:
""" Build fingerprinter """
# m_pre: log-power-Mel-spectrogram layer, S.
m_pre = get_melspec_layer(cfg, trainable=False)

# m_specaug: spec-augmentation layer.
m_specaug = get_specaug_chain_layer(cfg, trainable=False)
#assert(m_specaug.bypass==False) # Detachable by setting m_specaug.bypass.

# m_fp: fingerprinter g(f(.)).
m_fp = get_fingerprinter(cfg, trainable=False)

In [38]:
get_fingerprinter(cfg, trainable=False)