In [3]:
import numpy as np
import tensorflow as tf
assert tf.__version__ >= "2.0"
import keras

In [6]:
layer = keras.layers.LayerNormalization(axis=[1, 2])
layer.build([5, 2, 3])
print(layer.beta.shape)

print(layer.gamma.shape)


(2, 3)
(2, 3)


In [8]:
layer.beta

<tf.Variable 'beta:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [9]:
layer.gamma

<tf.Variable 'gamma:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [10]:
layer

In [ ]:
tf.keras.layers.Conv2D(hidden_ch,kernel_size=(1, 3), strides=strides[0],padding='SAME',dilation_rate=(1, 1),kernel_initializer='glorot_uniform',bias_initializer='zeros')

In [12]:
data = tf.constant(np.arange(10).reshape(5, 2) * 10, dtype=tf.float32)
print(data)

tf.Tensor(
[[ 0. 10.]
 [20. 30.]
 [40. 50.]
 [60. 70.]
 [80. 90.]], shape=(5, 2), dtype=float32)


In [15]:
layer = tf.keras.layers.LayerNormalization(axis=0)
output = layer(data)
print(output)

tf.Tensor(
[[-1.4142127  -1.4142127 ]
 [-0.70710635 -0.70710635]
 [ 0.          0.        ]
 [ 0.70710635  0.7071065 ]
 [ 1.4142127   1.4142128 ]], shape=(5, 2), dtype=float32)


In [20]:
layer = tf.keras.layers.LayerNormalization(axis=1)
output = layer(data)
print(output)

tf.Tensor(
[[-0.99998    0.99998  ]
 [-0.99998    0.99998  ]
 [-0.99998    0.99998  ]
 [-0.99998    0.99998  ]
 [-0.9999809  0.999979 ]], shape=(5, 2), dtype=float32)


In [17]:
layer = tf.keras.layers.LayerNormalization(axis=[0,1])
output = layer(data)
print(output)

tf.Tensor(
[[-1.5666981  -1.2185429 ]
 [-0.8703878  -0.5222327 ]
 [-0.17407757  0.17407756]
 [ 0.52223265  0.8703878 ]
 [ 1.2185429   1.5666981 ]], shape=(5, 2), dtype=float32)


In [19]:
print(layer.beta.shape)

(5, 2)


In [23]:
print(layer.beta)

<tf.Variable 'layer_normalization_9/beta:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>


In [24]:
print(layer.gamma.shape)

(2,)


In [22]:
print(layer.gamma)

<tf.Variable 'layer_normalization_9/gamma:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>
