In [5]:
import numpy as np

In [6]:
test_ids = np.load('/home/rodrigo/Documents/neural-audio-fp/logs/emb/Checks/100/test_ids.npy')
test_ids

array([14655, 21662,  7594, ..., 15722,  1097,  4538])

In [7]:
print(test_ids)

[14655 21662  7594 ... 15722  1097  4538]


In [3]:
raw_score = np.load('/home/rodrigo/Documents/neural-audio-fp/logs/emb/Checks/100/raw_score.npy')
raw_score

array([[1, 1, 1, ..., 1, 1, 1],
       [0, 0, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [4]:
query_shape = np.load('/home/rodrigo/Documents/neural-audio-fp/logs/emb/Checks/100/query_shape.npy')
query_shape

array([29500,   128])